import { getSession, signOut } from 'next-auth/client';
import Head from 'next/head';
import Image from 'next/image';
import { Navbar } from '../components/Navbar';
import { TodoInput } from '../components/TodoInput';

const Home = ({ session }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />
      <main>
        <TodoInput />
      </main>
    </div>
  );
};

export const getServerSideProps = async (context) => {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
};

export default Home;
