import { getSession, signOut } from 'next-auth/client';
import Head from 'next/head';
import Image from 'next/image';

const Home = ({ session }) => {
  console.log(session);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>Hello {session.user.name}</h1>
        <button onClick={() => signOut()}>Sign Out</button>
      </main>
    </div>
  );
};

export const getServerSideProps = async (context) => {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
};

export default Home;
